/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho_pratico;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.saxon.s9api.SaxonApiException;

/**
 *
 * @author gabriel
 */
public class Pesquisas extends javax.swing.JFrame {

    /**
     * Creates new form Pesquisas
     */
    public Pesquisas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dados de um Autor", "Autor por Código", "Autor por Nacionalidade", "Autor por Genero Preferido", "Livro por ISBN", "Livros de um Escritor", "Soma de Preços de um Autor", "Preços Superiores a", "Preços Inferiores a", "Numero de páginas e preço", " ", " ", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel2.setText("Resultados");

        jTextField2.setText("Nome do autor");
        jTextField2.setToolTipText("");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setText("2 Elemento da pesquisa");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        ArrayList res = new ArrayList();
        String x= String.valueOf(jComboBox1.getSelectedItem());
        String resultado;
        
        if(x.equals("Dados de um Autor"))
            {
                jTextField2.setText("Nome do autor");
                jTextField3.setVisible(false);
            }
            else if(x.equals("Codigo de um autor"))
            {
                jTextField2.setText("Nome do autor");
                jTextField3.setVisible(false);
            }
            else if(x.equals("Autor por Nacionalidade"))
            {
                jTextField2.setText("Nacionalidade");
                jTextField3.setVisible(false);
            }
            else if(x.equals("Autor por Genero Preferido"))
            {
                jTextField2.setText("Genero");
                jTextField3.setVisible(false);
            }
            else if(x.equals("Livros de um Escritor"))
            {
                jTextField2.setText("Escritor");
                jTextField3.setVisible(false);
            }
            else if(x.equals("Soma de Preços de um Autor"))
            {
                jTextField2.setText("Código de escritor");
                jTextField3.setVisible(false);
            }
            else if(x.equals("Preços Superiores a"))
            {
                jTextField2.setText("Montante");
                jTextField3.setVisible(false);
            }
            else if(x.equals("Preços Inferiores a"))
            {
                jTextField2.setText("Montante");
                jTextField3.setVisible(false);
            }
            else if(x.equals("Numero de páginas e preço"))
            {
                jTextField2.setText("Numero de páginas");
                jTextField3.setVisible(true);
                jTextField3.setText("Montante");
            }
            else if(x.equals("Livro por ISBN"))
            {
                jTextField2.setText("ISBN");
                jTextField3.setVisible(false);
            }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
        jTextField3.setVisible(false);
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList res = new ArrayList();
        String x= String.valueOf(jComboBox1.getSelectedItem());
        String resultado;
        
        try {
            if(x.equals("Dados de um Autor"))
            {
                Autores pessoa = new Autores();
                ArrayList <Livros> l = new ArrayList <Livros>();
                String autor;
                StringBuilder resultado2 = new StringBuilder();
                
                resultado=Trabalho_Pratico.procuraNome(jTextField2.getText());
                
                if(resultado.equals("Sem resultados")){
                    autor = jTextField2.getText();
                    pessoa=Autores.getWikiFile(autor);
                    if(pessoa.getNome().equals("O nome que foi introduzido não é válido"))
                    {
                        resultado2.append(pessoa.getNome()).append("\n");
                        resultado2.append(pessoa.getID()).append("\n");
                        resultado2.append(pessoa.getData_nasc()).append("\n");
                        jTextArea2.setText(resultado2.toString());
                    }
                    else
                    {
                        l=Livros.getWookFile(autor);
                        pessoa.setID(l.get(0).getCodautor());
                        String adicionado = Autores.adicionaAutores(pessoa);
                        if(adicionado.equals("Sucesso"))
                        {
                            resultado2.append(pessoa.getNome()).append("\n");
                            resultado2.append(pessoa.getID()).append("\n");
                            resultado2.append(pessoa.getData_nasc()).append("\n");
                            jTextArea2.setText(resultado2.toString());
                        }
                        else
                            jTextArea2.setText("Autor já existe em ficheiro, mas a pesquisa não permite encontrar este.");
                    }
                }
                else
                    jTextArea2.setText(resultado);
            }
            else if(x.equals("Codigo de um autor"))
            {
                resultado=Trabalho_Pratico.procuraCodautor(jTextField2.getText());
                jTextArea2.setText(resultado);
            }
            else if(x.equals("Autor por Nacionalidade"))
            {
                    resultado=Trabalho_Pratico.procuraNacionalidade(jTextField2.getText());
                    jTextArea2.setText(resultado);
            }
            else if(x.equals("Autor por Genero Preferido"))
            {
                resultado=Trabalho_Pratico.procuraGenero(jTextField2.getText());
                jTextArea2.setText(resultado);
            }
            else if(x.equals("Livros de um Escritor"))
            {
                resultado=Trabalho_Pratico.procuraLivrosEscritor(jTextField2.getText());
                jTextArea2.setText(resultado);
            }
            else if(x.equals("Soma de Preços de um Autor"))
            {
                resultado=Trabalho_Pratico.somaPrecos(jTextField2.getText());
                jTextArea2.setText(resultado);
            }
            else if(x.equals("Preços Superiores a"))
            {
                resultado=Trabalho_Pratico.procuraPrecosMaiores(jTextField2.getText());
                jTextArea2.setText(resultado);
            }
            else if(x.equals("Preços Inferiores a"))
            {
                resultado=Trabalho_Pratico.procuraPrecosMenores(jTextField2.getText());
                jTextArea2.setText(resultado);
            }
            else if(x.equals("Numero de páginas e preço"))
            {
                resultado=Trabalho_Pratico.procuraPaginasPreco(jTextField2.getText(),jTextField3.getText());
                jTextArea2.setText(resultado);
            }
            else if(x.equals("Livro por ISBN"))
            {
                resultado=Trabalho_Pratico.procuraLivroISBN(jTextField2.getText());
                jTextArea2.setText(resultado);
            }
            else if(x.equals("Autor por Código"))
            {
                resultado=Trabalho_Pratico.procuraAutorPorCod(jTextField2.getText());
                jTextArea2.setText(resultado);
            }
        } catch (SaxonApiException ex) {
                Logger.getLogger(Pesquisas.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
            Logger.getLogger(Pesquisas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesquisas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
